### PR TITLE
feat: add wasmcmd pkg

### PR DESCRIPTION
**Pull request by ilgooz**
derived from tendermint/spm with some modifications.

### CODE REVIEW

**Review by lumtis — APPROVED** [review]
This looks good but we should rename the entire repo into `wasmcmd`.

`spm-extras` description says 
```
Additional packages that we can not keep under tendermint/spm because of incompatibility issues.
```
but if we eventually have another incompatibility with `go.mod` then we would even create another repo to keep this incompatibility separated apart as we did here for `wasm`

Or at least renaming it to `spm-wasm` to precise this will be all the stuff when you can import `wasm`

**Comment by ilgooz** [comment]
I believe it is better to keep this generic name for future proofing, one repo would be enough.

**Comment by fadeev** [comment]
We may rename things in the future. As long as users are able to install older versions, it should be fine.

**Comment by lubtd** [comment]
> I believe it is better to keep this generic name for future proofing, one repo would be enough.

There is no reason to keep a generic name if this has been specifically created for `wasm`

> We may rename things in the future. As long as users are able to install older versions, it should be fine.

This is not a no go, it just makes the repo name less descriptive IMO

**Pull request merged**
